"""empty message

Revision ID: 0d6a9b53831f
Revises: fa05cbb71ec9
Create Date: 2022-02-22 11:15:41.316641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d6a9b53831f'
down_revision = 'fa05cbb71ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('views', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'views')
    # ### end Alembic commands ###
