"""empty message

Revision ID: c719e4629bbb
Revises: 0d6a9b53831f
Create Date: 2022-02-22 11:34:54.567739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c719e4629bbb'
down_revision = '0d6a9b53831f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('created_at_date', sa.Date(), nullable=False))
    op.add_column('videos', sa.Column('created_at_time', sa.TIME(), nullable=False))
    op.drop_column('videos', 'created_at')
    op.drop_column('videos', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('videos', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('videos', 'created_at_time')
    op.drop_column('videos', 'created_at_date')
    # ### end Alembic commands ###
