"""empty message

Revision ID: 576055e294fc
Revises: 
Create Date: 2022-02-27 23:01:10.254412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576055e294fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'subscriber_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'subscriber_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
