"""empty message

Revision ID: e8471d53e9ad
Revises: 576055e294fc
Create Date: 2022-02-28 04:04:15.503810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8471d53e9ad'
down_revision = '576055e294fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscriber_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscriber_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
